# fly.toml app configuration file generated for hyre-worker-nestjs on 2026-01-03T09:48:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyre-worker-nestjs'
primary_region = 'lhr'

[env]
  TZ = 'Africa/Lagos'
  OPERATIONS_EMAIL = 'support@tripdly.com'
  TWILIO_BOOKING_STATUS_UPDATE_CONTENT_SID = 'HX199f51dda921d5a781b2424b82b931a5'
  TWILIO_CLIENT_BOOKING_LEG_START_REMINDER_CONTENT_SID = 'HX862149f716a87ae25ce34151140bfc60'
  TWILIO_CHAUFFEUR_BOOKING_LEG_START_REMINDER_CONTENT_SID = 'HX8d44b0747c995713d129d77f4cc3c860'
  TWILIO_CLIENT_BOOKING_LEG_END_REMINDER_CONTENT_SID = 'HX0c8470054c0ff1a0b43c06fe196e2ec3'
  TWILIO_CHAUFFEUR_BOOKING_LEG_END_REMINDER_CONTENT_SID = 'HX9faf29432a18e9f8f8283a5e281e5a3c'
  TWILIO_BOOKING_CONFIRMATION_CONTENT_SID = 'HXac9f0b83ee03d47fe2f2969173dac354'
  TWILIO_BOOKING_CANCELLATION_CLIENT_CONTENT_SID = 'HXd32930f086ad7e2c3ac976e245c314f9'
  TWILIO_BOOKING_CANCELLATION_FLEET_OWNER_CONTENT_SID = 'HX5ad3e909d6c011f24e00f4706a78a90e'
  TWILIO_FLEET_OWNER_BOOKING_NOTIFICATION_CONTENT_SID = 'HXaeda40fabb6c33f323c1f101e0a10165'
  TWILIO_BOOKING_EXTENSION_CONFIRMATION_CONTENT_SID = 'HXaeda40fabb6c33f323c1f101e0a10165'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
