export enum JobErrorCodes {
  INVALID_TYPE = "JOB.VALIDATION.INVALID_TYPE",
  ENQUEUE_FAILED = "JOB.QUEUE.ENQUEUE_FAILED",
  MANUAL_TRIGGERS_DISABLED = "JOB.AUTH.MANUAL_TRIGGERS_DISABLED",
  RATE_LIMIT_EXCEEDED = "JOB.RATE_LIMIT.EXCEEDED",
}
